# NumPy Tutorial
Practice notebook based on the CS231n Python NumPy Tutorial: https://cs231n.github.io/python-numpy-tutorial/

Covers: **NumPy**, **Arrays**, **Array indexing**, **Datatypes**, **Array math**, and **Broadcasting**.

## NumPy
NumPy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

### Importing NumPy

In [1]:
import sys
print(sys.executable)

c:\Users\athar\anaconda3\envs\ece-5831-2026\python.exe


In [2]:
%pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np
print("NumPy version:", np.__version__)

NumPy version: 2.5.3


## Arrays
A numpy array is a grid of values, all of the same type, indexed by a tuple of nonnegative integers. The number of dimensions is the *rank*; the *shape* is a tuple giving the size along each dimension.

### Creating arrays from Python lists

In [4]:
a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # <class 'numpy.ndarray'>
print(a.shape)             # (3,)
print(a[0], a[1], a[2])
a[0] = 5                   # Change an element of the array
print(a)

b = np.array([[1, 2, 3], [4, 5, 6]])   # Create a rank 2 array
print(b.shape)                          # (2, 3)
print(b[0, 0], b[0, 1], b[1, 0])

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


### Built-in functions to create arrays

In [5]:
a = np.zeros((2, 2))          # Array of all zeros
print(a)

b = np.ones((1, 2))           # Array of all ones
print(b)

c = np.full((2, 2), 7)        # Constant array
print(c)

d = np.eye(2)                 # 2x2 identity matrix
print(d)

e = np.random.random((2, 2))  # Array filled with random values
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.2248083  0.33626695]
 [0.34164164 0.5580412 ]]


## Array Indexing
NumPy offers several ways to index into arrays: slicing, integer array indexing, and boolean array indexing.

### Slicing

In [6]:
# Rank 2 array with shape (3, 4)
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Pull out the subarray of the first 2 rows and columns 1-2
b = a[:2, 1:3]
print(b)

# A slice is a view into the same data - modifying it modifies the original array
print(a[0, 1])
b[0, 0] = 77
print(a[0, 1])

[[2 3]
 [6 7]]
2
77


### Mixing integer indexing with slice indexing

In [7]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

row_r1 = a[1, :]     # Rank 1 view of the second row
row_r2 = a[1:2, :]   # Rank 2 view of the second row
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


### Integer array indexing

In [8]:
a = np.array([[1, 2], [3, 4], [5, 6]])

print(a[[0, 1, 2], [0, 1, 0]])  # [1 4 5]
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # equivalent

print(a[[0, 0], [1, 1]])  # [2 2] - can reuse the same element

# Selecting/mutating one element from each row of a matrix
a2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
b = np.array([0, 2, 0, 1])
print(a2[np.arange(4), b])
a2[np.arange(4), b] += 10
print(a2)

[1 4 5]
[1 4 5]
[2 2]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


### Boolean array indexing

In [9]:
a = np.array([[1, 2], [3, 4], [5, 6]])

bool_idx = (a > 2)
print(bool_idx)

print(a[bool_idx])   # [3 4 5 6]
print(a[a > 2])       # equivalent, more concise

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


## Datatypes
Every numpy array is a grid of elements of the same type. NumPy tries to guess a datatype when you create an array, but you can also specify it explicitly.

### Letting NumPy choose vs. forcing a dtype

In [10]:
x = np.array([1, 2])          # Let numpy choose the datatype
print(x.dtype)

x = np.array([1.0, 2.0])      # Let numpy choose the datatype
print(x.dtype)

x = np.array([1, 2], dtype=np.int64)  # Force a particular datatype
print(x.dtype)

x = np.array([1, 2], dtype=np.float32)
print(x.dtype, x)

int64
float64
int64
float32 [1. 2.]


## Array Math
Basic mathematical functions operate elementwise on arrays, available both as operator overloads and as functions in the numpy module.

### Elementwise operations

In [11]:
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)

print(x + y)
print(np.add(x, y))

print(x - y)
print(np.subtract(x, y))

print(x * y)
print(np.multiply(x, y))

print(x / y)
print(np.divide(x, y))

print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


### Dot product (inner / matrix products)

In [12]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

# Inner product of vectors
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


### sum() and other aggregate functions

In [13]:
x = np.array([[1, 2], [3, 4]])

print(np.sum(x))          # sum of all elements
print(np.sum(x, axis=0))  # sum of each column
print(np.sum(x, axis=1))  # sum of each row

10
[4 6]
[3 7]


### Transposing arrays

In [14]:
x = np.array([[1, 2], [3, 4]])
print(x)
print(x.T)

# Transposing a rank 1 array does nothing
v = np.array([1, 2, 3])
print(v)
print(v.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


## Broadcasting
Broadcasting lets numpy work with arrays of different shapes when performing arithmetic operations, without actually copying data.

### Adding a vector to each row with an explicit loop

In [15]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)

for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


### The same result using np.tile (no broadcasting)

In [16]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])

vv = np.tile(v, (4, 1))   # Stack 4 copies of v
print(vv)

y = x + vv
print(y)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


### The same result using broadcasting

In [17]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])

y = x + v   # Broadcasting: v (shape (3,)) is applied to each row of x (shape (4, 3))
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


### More broadcasting applications

In [18]:
v = np.array([1, 2, 3])   # shape (3,)
w = np.array([4, 5])       # shape (2,)

# Outer product: reshape v to (3, 1), broadcast against w -> shape (3, 2)
print(np.reshape(v, (3, 1)) * w)

# Add a vector to each row of a matrix
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x + v)

# Add a vector to each column of a matrix
print((x.T + w).T)
print(x + np.reshape(w, (2, 1)))

# Multiply a matrix by a scalar
print(x * 2)

[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]
